apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testvault.fullname" . }}
  labels:
    {{- include "testvault.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "testvault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testvault.selectorLabels" . | nindent 8 }}
        component: vaultd
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testvault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-dir
          emptyDir:
            medium: Memory
        - name: data-dir
          emptyDir:
            medium: Memory
      containers:
        - name: {{ .Chart.Name }}
          args: ["server", "-dev", "-log-level=trace", "-dev-no-store-token"]
          env:
          - name: VAULT_LOCAL_CONFIG
            value: "{\"backend\": {\"file\": {\"path\": \"/vault/file\"}}, \"disable_mlock\": true, \"default_lease_ttl\": \"168h\", \"max_lease_ttl\": \"720h\"}"
          - name: "SKIP_CHOWN" 
            value: "true" 
          - name: "SKIP_SETCAP" 
            value: "true"
          - name: VAULT_ADDR
            value: http://127.0.0.1:8080
          - name: VAULT_API_ADDR
            value: http://127.0.0.1:8080
          - name: HOME
            value: /vault
          - name: VAULT_DEV_LISTEN_ADDRESS
            value: 0.0.0.0:8080
          - name: VAULT_DEV_ROOT_TOKEN_ID
            value: test
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /vault/config
              name: config-dir
            - mountPath: /vault/file
              name: data-dir
          ports:
            - name: vault
              containerPort: 8080
              protocol: TCP
            - name: vault-cluster
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.daemon | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
