apiVersion: v1
kind: Pod
metadata:
  name: {{ include "testvault.fullname" . }}-vaultcli
  labels:
    {{- include "testvault.labels" . | nindent 4 }}
    component: cli
spec:
  containers:
  - command:
    - sleep
    - infinity and beyond
    env:
      - name: VAULT_ADDR
        value: http://{{ include "testvault.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}
    image: vault
    name: vaultcli
    resources:
      {{- toYaml .Values.resources.cli | nindent 6 }}